name: marriage_haal
description: Marriage Hall Booking App
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # url_launcher: ^6.0.9
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  google_fonts: ^8.0.1
  # carousel_slider: ^4.2.1
  carousel_slider: ^5.0.0
  share_plus: 12.0.1
  cross_file: ^0.3.2
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/slide1.jpg
    - assets/images/slide2.jpg
    - assets/images/slide3.jpg
    - assets/images/background.jpg
    - assets/images/jungle.jpg
    - assets/images/halls/hall3.jpg
    - assets/images/wallpaper.jpg
    - assets/images/home_bg.jpg
    - assets/sounds/tap.mp3

    # ===== Home Background =====
    - assets/images/home_bg.jpg

    # ===== Dishes (Food + Drinks) =====
    - assets/images/dishes/aloo_finger.jpg
    - assets/images/dishes/chili_paneer.jpg
    - assets/images/dishes/hakka_noodles.jpg
    - assets/images/dishes/channa_masala.jpg
    - assets/images/dishes/butter_chicken.jpg
    - assets/images/dishes/palak_chicken.jpg
    - assets/images/dishes/gulab_jamun.jpg
    - assets/images/dishes/kheer.jpg
    - assets/images/dishes/gajar_ka_halwa.jpg
    - assets/images/dishes/coke.jpg
    - assets/images/dishes/pepsi.jpg
    - assets/images/dishes/lassi.jpg

    # ===== Cities =====
    - assets/images/cities/islamabad.jpg
    - assets/images/cities/lahore.jpg
    - assets/images/cities/karachi.jpg
    - assets/images/cities/faisalabad.jpg
    - assets/images/cities/rawalpindi.jpg

    # ===== Halls =====
    - assets/images/halls/hall1.jpg
    - assets/images/halls/hall2.jpg
    - assets/images/halls/hall3.jpg
    - assets/images/halls/hall4.jpg

    # ===== Functions =====
    - assets/images/mehndi.jpg
    - assets/images/barat.jpg
    - assets/images/walima.jpg
    - assets/images/mehfil.jpg
    - assets/images/others.jpg

